# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - topicwebapp

on:
  push:
    branches:
      - api
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mrqnlpapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a21727ed507149288679253a28a57f13 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ce5a9a73516f4953a6e1ad223aae868c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mrqnlpapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a21727ed507149288679253a28a57f13 }}/topicwepapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'topicwebapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_65dd10b1e9e9460c85319b0e3ca4740e }}
        images: 'mrqnlpapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a21727ed507149288679253a28a57f13 }}/topicwepapp:${{ github.sha }}'